parameters:
#    oist_web_auth.example.class: OIST\WebAuthBundle\Example

services:
#    oist_web_auth.example:
#        class: %oist_web_auth.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
